[package]
name = "q6"
version = "0.1.0"
authors = ["Jeff Zarnett <jzarnett@uwaterloo.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rand = "0.8.3"
